### ISSUE TITLE
csgo-vulkan-fix no works for me

### ISSUE THREAD

**Issue by 3ri4nG0ld** [hyprwm/hyprland-plugins#1]
I usually start CSGO using Gamescope so I can adjust the resolution, but I have several errors with the keyboard and mouse (if I press keys and move at the same time the mouse moves randomly), I used to run it with x11 using `SDL_VIDEODRIVER=x11`. but I needed to specify the primary monitor using `xrandr --output XWAYLAND1 --primary`, but in some update this was broken and now shows 
```
X Failed request error: BadMatch (invalid parameter attributes)
  Major opcode of failed request: 140 (RANDR)
  Minor opcode of failed request: 7 (RRSetScreenSize)
  Serial number of failed request: 36
  Current serial number in the output stream: 37
```
I have added this to my Hyprland configuration:
```
exec-once=hyprctl plugin load ~/.config/hypr/plugins/csgo-vulkan-fix.so

plugin {
    csgo-vulkan-fix {
        res_w = 1920
        res_h = 1080
    }
}
```
and I have tried to start CSGO both using:
`SDL_VIDEODRIVER=x11 gamemoderun %command% -window -w 1920 -h 1080 -vulkan -novid -nojoy +fps_max 160 +fps_max_menu 160 -high +mat_disable_fancy_blending 1 +cl_forcepreload 1 -limitvsconst -forcenovsync +r_dynamic 0`
As using :
`LD_PRELOAD="/usr/lib/libSDL2-2.0.so" gamemoderun %command% -window -w 1920 -h 1080 -vulkan -novid -nojoy +fps_max 160 +fps_max_menu 160 -high +mat_disable_fancy_blending 1 +cl_forcepreload 1 -limitvsconst -forcenovsync +r_dynamic 0`

I don't know what to do anymore, it is very uncomfortable to play with gamescope problems. 😢

**Comment by 3ri4nG0ld** [comment]
Ok, I have managed to get the resolution to appear in the game, but it does not apply, it may be because the monitor that is detecting as primary is 1440x900(16:10), but I'm not sure.

I have started using : 
`LD_PRELOAD="/usr/lib/libSDL2-2.0.so" gamemoderun mangohud %command% -window -w 1920 -h 1080 -vulkan -novid -nojoy +fps_max 160 +fps_max_menu 160 -high +mat_disable_fancy_blending 1 +cl_forcepreload 1 -limitvsconst -forcenovsync +r_dynamic 0`

And by default the resolution is like this:
![imagen](https://user-images.githubusercontent.com/24411137/225371011-05bee8f8-8191-4805-acd5-605987da6aee.png)

But if I change the aspect ratio to 16:9, I can select 1920x1080, but when I apply it does not apply it.
![imagen](https://user-images.githubusercontent.com/24411137/225371520-4c754c72-5617-469e-88da-4071ea1ca0f5.png)

**Comment by vaxerski** [comment]
`LD_PRELOAD="" MANGOHUD_CONFIG="fps=1,frame_timing=1,cpu_stats=0,gpu_stats=0,font_size=18,background_alpha=0.1" mangohud %command% -novid -nojoy -high -tickrate 102.4 -fullscreen -window -w 1680 -h 1050 -vulkan +cl_forcepreload 1 +r_dynamic 0 -threads 8 -novid -nojoy -high -console`

(adjust w and h)

fullscreen manually

should work

**Comment by 3ri4nG0ld** [comment]
It does not seem to work, when using : 
`LD_PRELOAD="" MANGOHUD_CONFIG="fps=1,frame_timing=1,cpu_stats=0,gpu_stats=0,font_size=18,background_alpha=0.1" mangohud %command% -novid -nojoy -high -tickrate 102.4 -fullscreen -window -w 1680 -h 1050 -vulkan +cl_forcepreload 1 +r_dynamic 0 -threads 8 -novid -nojoy -high -console`
gives the following error:
![imagen](https://user-images.githubusercontent.com/24411137/230225984-2e484f63-aba4-4777-8c54-7804b04ed681.png)
 and for some reason if I use `LD_PRELOAD="/usr/lib/libSDL2-2.0.so"` as I did before to force it to work in wayland it just won't start.

The good thing is that I managed to get it to work in x11 by setting the 1080p monitor as the main monitor.
for some reason if my HDMI-A-1 monitor is somewhere other than 0,0 it gives error when modifying anything with xrandr
and therefore gave the error:
```
X Failed request error: BadMatch (invalid parameter attributes)
  Major opcode of failed request: 140 (RANDR)
  Minor opcode of failed request: 7 (RRSetScreenSize)
  Serial number of failed request: 36
  Current serial number in the output stream: 37
```
but I solved it by executing these 3 commands at startup:
```
wlr-randr --output HDMI-A-1 --pos 0,0
xrandr --output DP-1 --primary
wlr-randr --output HDMI-A-1 --pos 3286,300
```

**Comment by vaxerski** [comment]
Why are you launching it with SDL_VIDEODRIVER=wayland? Just run csgo in xwayland.

**Comment by 3ri4nG0ld** [comment]
Currently I can run it with SDL_VIDEODRIVER=x11 , but I thought the purpose of this plugin was to fix the resolution when running with SDL_VIDEODRIVER=wayland, wasn't it?

**Comment by vaxerski** [comment]
nope, it fixes the mouse input with non-native resolutions in vulkan

**Comment by 3ri4nG0ld** [comment]
ha xD then it's my fault, I didn't interpret it correctly.
