### ISSUE TITLE
plugins won't compile

### ISSUE THREAD

**Issue by fearlessgeekmedia** [hyprwm/hyprland-plugins#10]
I'm on EndeavourOS here, the Sway community edition, though I've installed Hyprland.

I'm having trouble with compiling the plugins. For example, hyprbars

make: Entering directory '/home/fearlessgeek/hyprland-plugins/hyprbars'
g++ -shared -fPIC --no-gnu-unique main.cpp barDeco.cpp -o hyprbars.so -g -I "/usr/include/pixman-1" -I "/usr/include/libdrm" -I "" -I "/subprojects/wlroots/include" -I "/subprojects/wlroots/include" -I "/subprojects/wlroots/build/include" -std=c++23
main.cpp:6:10: fatal error: src/Compositor.hpp: No such file or directory
    6 | #include <src/Compositor.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from barDeco.cpp:1:
barDeco.hpp:5:10: fatal error: src/render/decorations/IHyprWindowDecoration.hpp: No such file or directory
    5 | #include <src/render/decorations/IHyprWindowDecoration.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:6: all] Error 1
make: Leaving directory '/home/fearlessgeek/hyprland-plugins/hyprbars'

**Comment by vaxerski** [comment]
https://wiki.hyprland.org/Plugins/Using-Plugins/#compiling-official-plugins

You didn't export hl sources

**Comment by fearlessgeekmedia** [comment]
OK, thanks!
