### ISSUE TITLE
Hyprbars: Hyprland crashes when windows get too small

### ISSUE THREAD

**Issue by Liassica** [hyprwm/hyprland-plugins#101]
When using Hyprbars, Hyprland's process will crash if the windows get too small (i.e. open too many on one workspace). This does not seem to happen when Hyprbars is disabled.

The error given is:
```
[CRITICAL] 
==================================
ASSERTION FAILED! 

Tried to render rect with width/height < 0!

at: line 716 in OpenGL.cpp
```

Crash reports (tried it many times to make sure):
[hyprlandCrashReport2211.txt](https://github.com/hyprwm/hyprland-plugins/files/14727479/hyprlandCrashReport2211.txt)
[hyprlandCrashReport28186.txt](https://github.com/hyprwm/hyprland-plugins/files/14727480/hyprlandCrashReport28186.txt)
[hyprlandCrashReport31794.txt](https://github.com/hyprwm/hyprland-plugins/files/14727483/hyprlandCrashReport31794.txt)
[hyprlandCrashReport32956.txt](https://github.com/hyprwm/hyprland-plugins/files/14727488/hyprlandCrashReport32956.txt)

**Comment by vaxerski** [comment]
try with above

**Comment by Liassica** [comment]
Seems to be fixed, thanks!
