### ISSUE TITLE
hyprexpo: second monitor not respecting the position of the current workspace on that monitor 

### ISSUE THREAD

**Issue by MysticBytes786** [hyprwm/hyprland-plugins#110]
## problem

The second monitor is mirroring the main monitor. It doesn't respect the position of the second monitor. 

### main monitor
![1712175257](https://github.com/hyprwm/hyprland-plugins/assets/30713087/987c4543-f98b-451e-87a8-4cedfebf9695)

### second monitor
![1712175274](https://github.com/hyprwm/hyprland-plugins/assets/30713087/de885b8f-df7b-48c7-8707-a70a8c8afad7)
----

### second monitor
![1712175296](https://github.com/hyprwm/hyprland-plugins/assets/30713087/b0e9d55a-fa5b-48f0-af94-083131df8bbd)

---
Also there's  small drop frames on the second monitor. It could be nvidia :)

**Comment by vaxerski** [comment]
right. But if you open expo on the second monitor does it work on the second?

**Comment by MysticBytes786** [comment]
yep but the same will happen with the main monitor. Also, because my second monitor having different aspect ratio the layout is broken.

Maybe it's better to have option only the active monitor(hovering mouse) will show the workspace on that monitor

https://github.com/hyprwm/hyprland-plugins/assets/30713087/1f2cf0c5-7840-4af1-a48f-8913d40c736f

**Comment by vaxerski** [comment]
check now. Overlay should only render on the monitor it was opened on (as I was intending to have it anyways)

**Comment by MysticBytes786** [comment]
It works flawlessly now. Thanks!
