### ISSUE TITLE
hyprexpo: switching workspace while hyprexpo is open crashes Hyprland

### ISSUE THREAD

**Issue by alba4k** [hyprwm/hyprland-plugins#112]
Pretty much what the title says (I'm using keyboard bindings)

[hyprlandCrashReport174650.txt](https://github.com/hyprwm/hyprland-plugins/files/14858540/hyprlandCrashReport174650.txt)

**Comment by vaxerski** [comment]
you need to be more specific; it doesn't for me

**Comment by alba4k** [comment]
Try to open hyprexpo while on ws1, and switch back and forward between 1 and 2 a couple of times. Does the job for me

**Comment by alba4k** [comment]
Doesn't crash anymore on my side either, may just be a random thing.

As before tho, it looks quite weird (Like, say I open it while on ws1 and then switch to ws2, I can't switch back to ws1). Is this the same on your machine?

**Comment by vaxerski** [comment]
yea it generally is buggy when you switch workspaces with a keybind. I might forcefully disable it, or make it close the overlay.

**Comment by alba4k** [comment]
both options make equally sense

throw a coin

or, if you wanna do it with style, close the overlay with the same animation that would play if you had clicked on the selected workspace (which I guess requires intercepting which workspace the bind was pointing to)

**Comment by alba4k** [comment]
Ok I think it just looks like the window from all workspaces are just being put into the same workspace

![immagine](https://github.com/hyprwm/hyprland-plugins/assets/84153269/959c4511-61b4-4764-8ebd-82bf0731c908)

in this image I was on ws6 and tried switching to 1 2 and 3

**Hyprland crashed once I tried to press on ws4 to switch to that.**

**Comment by vaxerski** [comment]
> if you wanna do it with style, close the overlay with the same animation that would play if you had clicked on the selected workspace (which I guess requires intercepting which workspace the bind was pointing to)

that's literally option 2

**Comment by vaxerski** [comment]
also crash this crash that but no crash report where crash report

**Comment by vaxerski** [comment]
thoughts?

**Comment by alba4k** [comment]
crash report is in the original issue lmao

**Comment by alba4k** [comment]
Works as almost perfectly, but the weird behavior is still visible if changing workspace again during the closing animation


https://github.com/hyprwm/hyprland-plugins/assets/84153269/711b07b4-a83f-4d8d-90de-f8cd1e1652a8

**Comment by alba4k** [comment]
Agree, but I guess it deserved being pointed out.
