### ISSUE TITLE
hyprexpo: bg_col has no effect?

### ISSUE THREAD

**Issue by alba4k** [hyprwm/hyprland-plugins#114]
I have `bg_col = rgb(1e1e2e)` in my config, Yet this is what hyprexpo looks like
![immagine](https://github.com/hyprwm/hyprland-plugins/assets/84153269/8bd6d610-a579-4af9-9b4d-ddf889aafacd)
(My wallpaper is exactly that color, meaning that the gaps are a different color)

**Comment by vaxerski** [comment]
correct.
