### ISSUE TITLE
hyprexpo: stay at current workspace by default

### ISSUE THREAD

**Issue by leon-erd** [hyprwm/hyprland-plugins#116]
I'm using hyprexpo with `workspace_method = "first 1"`. 
When opening hyprexpo with keybind/gesture and then closing it again with keybind/gesture (and not clicking on the workspace) it always returns to workspace 1 even if opened from another workspace (i.e. 5). I would assume it to return to the workspace it was opened from (i.e. 5) by default.
Maybe related to the weird behaviour described by https://github.com/hyprwm/hyprland-plugins/issues/113#issuecomment-2035611214?

**Comment by vaxerski** [comment]
yea keep it in #113, it's bugged atm
