### ISSUE TITLE
hyprexpo: can't load the plugin

### ISSUE THREAD

**Issue by LOSEARDES77** [hyprwm/hyprland-plugins#120]
when i try to load the plugin with hyprpm it says everything was ok but when doing `hyprctl plugin list` says no plugins loaded

![image](https://github.com/hyprwm/hyprland-plugins/assets/84414230/87d6b823-eaa7-494b-b48c-74e5ada7cbc7)

Logs i found usefull:
```
[LOG] [functionhook] assembler returned:

[LOG] [functionhook] assembler returned:
/tmp/hypr/.hookcode.asm: Assembler messages:
/tmp/hypr/.hookcode.asm:7: Error: operand type mismatch for `movabs'

[ERR] [functionhook] failed, unsupported asm / failed assembling:
push %r12
push %rbp
mov %rsi, %rbp
push %rbx
mov %rdi, %rbx
sub $0x60, %rsp
movzx 0x291fbb(%rip), %eax

[ERR]  [PluginSystem] Plugin /home/loseardes77/.local/share/hyprpm/hyprland-plugins/hyprexpo.so (Handle 1f09290) crashed in init. Unloading.
[LOG]  [PluginSystem] Plugin  unloaded.
```

I'm on latest git version of hyprland

i have tryed to compile separated and load with hyprctl but i get the same logs and this error message on hyprctl:
```
error in loading plugin, last error: Plugin /home/loseardes77/Repos/hyprland-plugins/hyprexpo/hyprexpo.so could not be loaded: plugin crashed/threw in main: [he] Failed initializing hooks
```

**Comment by vaxerski** [comment]
https://github.com/hyprwm/Hyprland/blob/main/CMakeLists.txt#L95-L95

try compiling hyprland with `-fno-pie -fno-pic`

**Comment by LOSEARDES77** [comment]
> https://github.com/hyprwm/Hyprland/blob/main/CMakeLists.txt#L95-L95
> 
> try compiling hyprland with `-no-pie -fno-pic`

I get the exact same logs

**Comment by LOSEARDES77** [comment]
I thought this had to be with my pc.
So is a bug with the hook system?

**Comment by vaxerski** [comment]
yah

**Comment by LOSEARDES77** [comment]
Still can't see why it works for other people then but i believe in you to fix it <3

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/hyprland-plugins/files/14874215/patch.txt)
try this for hyprland

**Comment by LOSEARDES77** [comment]
Do i need to refresh the Hyprland session?

**Comment by vaxerski** [comment]
refresh? it's a patch, recompile it with it

**Comment by LOSEARDES77** [comment]
I mean after compiling installing exit hyprland and re enter or only the Headers is what matters?

**Comment by vaxerski** [comment]
yea re enter its a code patch

**Comment by LOSEARDES77** [comment]
```
[LOG] [functionhook] assembler returned:

[LOG] [functionhook] assembler returned:
/tmp/hypr/.hookcode.asm: Assembler messages:
/tmp/hypr/.hookcode.asm:7: Error: no such instruction: `movz -0x7f6d71c27235(%rip),%eax'

[ERR] [functionhook] failed, unsupported asm / failed assembling:
push %r12
push %rbp
mov %rsi, %rbp
push %rbx
mov %rdi, %rbx
sub $0x60, %rsp
movzx 0x29230b(%rip), %eax

[ERR]  [PluginSystem] Plugin /home/loseardes77/Repos/hyprland-plugins/hyprexpo/hyprexpo.so (Handle 21f84e0) crashed in init. Unloading.
[LOG]  [PluginSystem] Plugin  unloaded.
```

**Comment by LOSEARDES77** [comment]
I recompiled the plugin too with new headers just in case

**Comment by vaxerski** [comment]
right that won't work... hm.

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/hyprland-plugins/files/14875043/patch.txt)
try this

**Comment by LOSEARDES77** [comment]
What shoudl i answer here when patching?
![image](https://github.com/hyprwm/hyprland-plugins/assets/84414230/74f1cc81-90c8-479b-ade6-536d51eb18a0)

**Comment by vaxerski** [comment]
oops I did a dumb and molten 2 patches together. Gimme sec

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/hyprland-plugins/files/14875153/patch.txt)
fixed

**Comment by LOSEARDES77** [comment]
the patch is only for the HookSystem.cpp and hpp right?

**Comment by LOSEARDES77** [comment]
Ok now works fine.
Thanks you!

**Comment by vaxerski** [comment]
well wait for me to commit it lol

**Comment by vaxerski** [comment]
done, enjoy

**Comment by gptlang** [comment]
![image](https://github.com/hyprwm/hyprland-plugins/assets/121417512/09f15853-057a-46ed-bd8c-a82cb953a237)

I still seem to be getting the same problem
