### ISSUE TITLE
hyprexp: Failed to build.

### ISSUE THREAD

**Issue by spynetS** [hyprwm/hyprland-plugins#121]
When i try to add the plugins the hyprexpo plugin failed to build.

**Logs**

 → Building hyprexpo                                                                                                                                                          
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╍━━━━━━━━━━━━━━━━━━━  3 / 5  Building plugin(s)[v] shell returned:  -> cd /tmp/hyprpm/new && PKG_CONFIG_PATH="/home/spy/.local/share/hyprpm/headersRoot/share/pkgconfig" make -C hyprexpo all
make: Entering directory '/tmp/hyprpm/new'
make: *** hyprexpo: No such file or directory.  Stop.
make: Leaving directory '/tmp/hyprpm/new'

✖ Plugin hyprexpo failed to build.

**Comment by CRAG666** [comment]
Same error

**Comment by vaxerski** [comment]
you need to be on git
