### ISSUE TITLE
[Feature request] Add support for released Hyprland (not hyprland-git)

### ISSUE THREAD

**Issue by YoYomec** [hyprwm/hyprland-plugins#131]
There is some problems with using `hyprland-git`, for exemple, it's only on the AUR, and it may be unstable.
That's why I ask if someone can do something like an other repo or a release system to make it work with Hyprland stable release when using `hyprpm`.
Thanks in advance.

**Comment by vaxerski** [comment]
it already works, though?

**Comment by YoYomec** [comment]
Ho.. I see. It's just this issues that confused me (see [Hyprland #5437](https://github.com/hyprwm/Hyprland/pull/5437)), so I can't build hyprexpo.
