### ISSUE TITLE
Hyprbars: Left title align doesn't work

### ISSUE THREAD

**Issue by Liassica** [hyprwm/hyprland-plugins#137]
When using Hyprbars ~from the flake~, the window title is center-aligned even when `bar_text_align` is set to left. ~This does not happen when using `hyprpm`, as far as I can tell.~ Other Hyprbars settings are applied as expected.

Update: https://github.com/hyprwm/hyprland-plugins/issues/137#issuecomment-2060076442.

**Comment by RoseHobgoblin** [comment]
I'm also receiving issues with the bar color not being as expected
![Screenshot_04-12-2024_3757](https://github.com/hyprwm/hyprland-plugins/assets/84164410/0d968ddc-e1a0-4780-9864-16e7486fbf2a)
![Screenshot_04-12-2024_3851](https://github.com/hyprwm/hyprland-plugins/assets/84164410/cd265a0e-fea4-4a9d-883b-29d522134c71)

**Comment by Liassica** [comment]
@RoseHobgoblin Should be `bar_color`, not `bar_colour`, no? :)

**Comment by Liassica** [comment]
For a bit more info on the main issue: this did not used to happen a few months ago but I couldn't tell you exactly when it started happening. I also haven't been able to test recently, but the last time I had Arch + Hyprland + Hyprbars working on my laptop (just under a month ago) `hyprpm`-installed Hyprbars worked as expected (while at the same time it did *not* using the flake on my NixOS system).

**Comment by fufexan** [comment]
Well we aren't patching it in any way.

**Comment by Liassica** [comment]
After seeing #139 I don't think this issue is unique to the flake. The mismatched behavior I was seeing was likely just due to mismatched Hyprbars/Hyprland versions between my two systems. After poking around in the code a bit I've found two solutions that seem to fix this (keep in mind I am not a programmer):
- Using a boolean value similar to how `BUTTONSRIGHT` is used
- Converting `*PALIGN` to a string before comparing its value (i.e. `std::string{*PALIGN} == "left"` instead of `*PALIGN == "left"`)

In both instances I am now able to use both left title align and center title align as expected. Other settings such as button alignment seem to continue to work as expected.
