### ISSUE TITLE
Unable to compile csgo-vulkan-fix after newest changes

### ISSUE THREAD

**Issue by gegnep** [hyprwm/hyprland-plugins#14]
Had to edit main.cpp headers to find the Hyprland headers (`#include </hyprland/src/...>` to `#include <../Hyprland/src/...>`, i did export hl headers before hand) to get it to compile, after which this error appears

`g++ -shared -fPIC --no-gnu-unique main.cpp -o csgo-vulkan-fix.so -g -I "/usr/include/pixman-1" -I "/usr/include/libdrm" -I "../Hyprland" -I "../Hyprland/protocols" -I "../Hyprland/subprojects/wlroots/include" -I "../Hyprland/subprojects/wlroots/build/include" -std=c++23
In file included from ../Hyprland/../Hyprland/src/includes.hpp:53,
                 from ../Hyprland/../Hyprland/src/defines.hpp:1,
                 from ../Hyprland/../Hyprland/src/Compositor.hpp:7,
                 from main.cpp:5:
../Hyprland/subprojects/wlroots/include/wlr/types/wlr_layer_shell_v1.h:16:10: fatal error: wlr-layer-shell-unstable-v1-protocol.h: No such file or directory
   16 | #include "wlr-layer-shell-unstable-v1-protocol.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:6: all] Error 1`

for fun, i commented out that header in the wlr source and another lib was missing as well

`g++ -shared -fPIC --no-gnu-unique main.cpp -o csgo-vulkan-fix.so -g -I "/usr/include/pixman-1" -I "/usr/include/libdrm" -I "../Hyprland" -I "../Hyprland/protocols" -I "../Hyprland/subprojects/wlroots/include" -I "../Hyprland/subprojects/wlroots/build/include" -std=c++23
In file included from ../Hyprland/subprojects/wlroots/include/wlr/types/wlr_xdg_decoration_v1.h:5,
                 from ../Hyprland/../Hyprland/src/includes.hpp:69,
                 from ../Hyprland/../Hyprland/src/defines.hpp:1,
                 from ../Hyprland/../Hyprland/src/Compositor.hpp:7,
                 from main.cpp:5:
../Hyprland/subprojects/wlroots/include/wlr/types/wlr_xdg_shell.h:16:10: fatal error: xdg-shell-protocol.h: No such file or directory
   16 | #include "xdg-shell-protocol.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:6: all] Error 1`

Deleting the git repo and following the wiki instructions from scratch reproduces these results

All done on a standard arch linux install

**Comment by vaxerski** [comment]
960a2ae4aa91b7ba2dae1c6608f4726bc0db1653

pull this commit...

**Comment by gegnep** [comment]
im getting this error on the latest commit of hyprland-plugins compiled against the latest commit on Hyprland and when i checkout v0.24.1

**Comment by vaxerski** [comment]
did you run `make pluginenv` in the cloned hl?

**Comment by frkli1965** [comment]
FWIW, I am experiencing the exact same issue since the offending commit.

I use a custom build script that hasn't changed since a number of successful builds prior to this commit btw.

**Comment by vaxerski** [comment]
should be fixed in hl. pull and make pluginenv again.

**Comment by gegnep** [comment]
after changing the headers to point to `../Hyprland/src` instead of `hyprland/src`  in main.cpp and globals.hpp and pulling latest hl commit it now compiles.

thanks for the dope wm vax!
