### ISSUE TITLE
[Feature request] Hypbars to auto-hide / auto-show

### ISSUE THREAD

**Issue by msmafra** [hyprwm/hyprland-plugins#141]
I really like hyprbars, but it feels form me as a new tiling WM user that it auto-hiding or hiding/show toggle with a keybind ro both would fit better, at least with my way of using Hyprland ( :) ).
The bar only appearing when hovering a window or even an specific region of a window would make easy to keep the visual very clean and let titlebar fiends like me use their way.

**Comment by vaxerski** [comment]
dupe of #74
