### ISSUE TITLE
plugins not loading

### ISSUE THREAD

**Issue by zebogan** [hyprwm/hyprland-plugins#145]
i run hyprpm reload and it says that the plugins load, but then i run hyprctl plugin list and it says no plugins loaded. how do i fix this?

**Comment by vaxerski** [comment]
you read the wiki and not open issues in the wrong repos https://wiki.hyprland.org/Plugins/Using-Plugins/#hyprpm

**Comment by zebogan** [comment]
a. i read the wiki, it doesn't say anything about this (i did all of the steps)
b. sorry i thought this would be the repo because it's a plugin problem

**Comment by vaxerski** [comment]
hyprpm is hosted under hyprland
