### ISSUE TITLE
hyprexpo infinite workspaces

### ISSUE THREAD

**Issue by sck1ss** [hyprwm/hyprland-plugins#148]
using hyprexpo i got it to 109
normally its 12
![20240418_15h56m45s_grim](https://github.com/hyprwm/hyprland-plugins/assets/86001650/c1642f23-d4fc-45bd-ba1c-18382b395c33)

**Comment by Z0achary** [comment]
you probably can get more

**Comment by vaxerski** [comment]
yea and?

**Comment by ninelore** [comment]
I think an option to limit workspaces would be nice

Some config ideas:
```
max_workspaces = 10
```

```
rows = 3 # workspaces would be colums * rows 
```

**Comment by Z0achary** [comment]
> vaxerksi: yea and?

:skull: 
so its an easter egg?

**Comment by zebogan** [comment]
if you do workspace_method = first 1 then it "fixes" this

**Comment by sck1ss** [comment]
eh i don't think this really matters anymore and it's probably fixed with the new updates, Closing.

**Comment by wagyourtail** [comment]
Yep, this was basically resolved a while ago with https://github.com/hyprwm/Hyprland/pull/5848
