### ISSUE TITLE
hyprexpo: limit number of workspaces?

### ISSUE THREAD

**Issue by hhhorb** [hyprwm/hyprland-plugins#149]
Wondering if I can just show 4 workspaces in the overview? I'm currently using the code found in the readme but it doesn;t show what options are available...

https://github.com/hyprwm/hyprland-plugins/tree/main/hyprexpo

Cool plugin!

**Comment by vaxerski** [comment]
![image](https://github.com/hyprwm/hyprland-plugins/assets/43317083/99e4b1ca-e130-4a61-b1c1-234c745476af)
3*3 = 9
2*2 = 4

**Comment by hhhorb** [comment]
Huh, good timing on my part? That was an instantaneous response.

`column = 2` is exactly what I wanted. Much obliged!
