### ISSUE TITLE
hyprwinwrap: not working as expected.

### ISSUE THREAD

**Issue by Rodrigo-Matuz** [hyprwm/hyprland-plugins#151]
Been trying to use hyprwinwrap to set a mpv video as background but it's not working, decided to follow the example in the README and that example also doesn't work 

## Expected:
kitty as background with cava 

## Result:
[Video](https://youtu.be/HOetbRlCLrw) (had to post on YT cuz more than 10MB)

Nvidia-dkms and all configuration is done. also tried some stuff on a [discord thread](https://discord.com/channels/961691461554950145/1221603197081223218)

Log file: https://ufile.io/8c7czz9b (link expires in 30d)

**Comment by vaxerski** [comment]
why not use mpvpaper for mpv?

**Comment by Rodrigo-Matuz** [comment]
![image](https://github.com/hyprwm/hyprland-plugins/assets/109036200/2b28a937-dc43-4f64-a255-93df98818f92)

After trying multiple times for both mpv and mpvpaper I decided to follow the readme

**Comment by Rodrigo-Matuz** [comment]
Managed to get mpvpaper to work in a old commit, for now I'm closing my issue.
Reference: [here](https://github.com/GhostNaN/mpvpaper/issues/70)
