### ISSUE TITLE
Extra buttons when reloading config

### ISSUE THREAD

**Issue by Roknor** [hyprwm/hyprland-plugins#157]
![2024-04-26T13:02:37,546284847+03:00](https://github.com/hyprwm/hyprland-plugins/assets/142147417/fd691b3b-61d2-44b3-bb39-5b36df3bb5e2)
Just as the title says, every time you reload the hyprland config, there is a new set of buttons spawned. I'm using the hyprland-git from AUR, which i update daily. This was not happening a week or so ago.

Here's my _plugin.conf_:
```
plugin {
    hyprbars {
        bar_height = 24
        bar_color = $background
        col.text = $foreground
        bar_title_enabled = yes
        bar_text_font = JetBrains Nerd Font
        bar_text_size = 10
        bar_text_align = center
        bar_buttons_alignment = right
        bar_part_of_window = yes
        bar_precedence_over_border = yes
        bar_padding = 5
        bar_button_padding = 5

        # hyprbars-button = color, size, on-click
        hyprbars-button = $color2, 16, 󰖭, hyprctl dispatch killactive
        hyprbars-button = $color5, 16, 󰖯, hyprctl dispatch fullscreen 1
        hyprbars-button = $color7, 16, 󰫳, hyprctl dispatch togglefloating
    }
}

```
This is not a showstopper, but still slightly annoying with my setup. Let me know if there's any other info i can provide.

**Comment by vaxerski** [comment]
dupe and already fixed #155
