### ISSUE TITLE
Hyprexpo bug with dual monitors

### ISSUE THREAD

**Issue by sam08sk** [hyprwm/hyprland-plugins#159]
First of all, excellent job with the plugin, much appreciated. I am facing a strange behavior while using an external monitor with my laptop. 

Issue: When I trigger Hyprexpo on the external monitor, the first one starts to blink and tear. When I focus on the first monitor it starts to paint the window

Note: It gets fixed when I trigger and toggle Hyprexpo on the first monitor as well.
Please see the attached video for a better explanation.

https://github.com/hyprwm/hyprland-plugins/assets/65501131/b20cf21e-fb2e-4844-ad7d-816a632e8966

It's not stopping my work or anything, just an odd behavior I wanted to report so it can be fixed at any rate.

**Comment by wagyourtail** [comment]
are you using 
```
workspace_method = first 1
```
iirc, it's caused by that, because suddenly both monitors are trying to use the same workspace

**Comment by sam08sk** [comment]
Hi @wagyourtail, thank you for the suggestion. Yes, it is set up exactly how you suggested. first Workspace goes to the laptop display and all the others go on the external monitor. I'll wait, possibly an update will fix this, it is not a deal breaker.

If I could have a way to have separate workspaces for each monitor, meaning 9 per monitor, I think it would resolve this issue.

**Comment by wagyourtail** [comment]
> I'll wait, possibly an update will fix this

actually. I already pr'd and got an update merged, because I was looking for a behavior similar to what you expected.
(https://github.com/hyprwm/Hyprland/pull/5848)
`workspace_method = first r~1`
