### ISSUE TITLE
hyprpm update 致命错误：处理浅克隆信息出错：4

### ISSUE THREAD

**Issue by 0a00** [hyprwm/hyprland-plugins#165]
![图片](https://github.com/hyprwm/hyprland-plugins/assets/59482058/15e5c690-a9dd-4e5c-a002-cedd7238afa8)

  ~                                                                                                                                                                                          11:21:1❯ hyprpm update -f -v
! Using --force, I hope you know what you are doing.
[v] version returned: Hyprland, built from branch  at commit cba1ade848feac44b2eda677503900639581c3f4  (props: bump version to 0.40.0).
Date: Sat May 4 15:42:32 2024
Tag: v0.40.0, commits: 4606

flags: (if any)

[v] parsed commit cba1ade848feac44b2eda677503900639581c3f4 at branch  on Sat May 4 15:42:32 2024, commits 4606

! Cloning https://github.com/hyprwm/hyprland, this might take a moment.
[v] will shallow since: 六 4月 27 15:42:32 2024

 ╍━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  0 / 5  Cloning the hyprland repository
✖ Could not clone the hyprland repository. shell returned:
正克隆到 'hyprland-fixmin'...
致命错误：处理浅克隆信息出错：4

**Comment by vaxerski** [comment]
we dont speak chinese
