### ISSUE TITLE
Hyprwinwrap - native transparency not respected

### ISSUE THREAD

**Issue by nnra6864** [hyprwm/hyprland-plugins#167]
### Hyprland Version
```
Hyprland, built from branch main at commit 38911d6df4977b6b00557cc887eb151d032e505b  (box: fix noNegativeSize).
Date: Fri May 10 13:59:01 2024
Tag: v0.40.0-55-g38911d6d, commits: 4661

flags: (if any)
```

### Description
When using hyprwinwrap to display an audio visualizer on the background(for example glava), windows that have native transparency(alacritty, kitty etc.) will block the rendering of such apps.
By native transparency I am referring to a setting in alacritty/kitty config.
If transparency is applied via a window rule it works fine.
This happens in the tiled mode only, if you make the window floating, it'll behave properly.
If you fullscreen the app whilst it's tiled, visualizer won't be rendered either, but if fullscreen while the app is floating it should still be visible.

### How to reproduce
Take an app with native window transparency and set it to a number less than 1.
Make sure that the app is not made transparent by the hyprland config via windowrule.
Have an app rendered on the background layer(can be achieved via hyprwinwrap).
Open the app with native transparency and put it in the tiling mode.
This should now block the rendering of a window placed on the background layer by hyprwinwrap.

### Without Hyrpland transparency
![image](https://github.com/hyprwm/hyprland-plugins/assets/104775644/7851d5ab-d62c-468a-8320-1beb7f5fedfd)

### With Hyprland transparency
![image](https://github.com/hyprwm/hyprland-plugins/assets/104775644/a942fe13-bc38-4811-8d27-4ce9068d8f7f)

**Comment by 71zenith** [comment]
I've been having the same issue with glava. would appreciate a fix :pray:

**Comment by nnra6864** [comment]
> I've been having the same issue with glava. would appreciate a fix 🙏

I just use Hyprland's transparency now.
It honestly does a good enough job and I can't say I had a hard time reading anything.
Been using 0.9 opacity for both my terminal and IDEs and it's readable and looks nice.
It's an issue if you wanna go for a more transparent look tho.

**Comment by atikiNBTW** [comment]
I dunno what happened, but this seems to be fixed

**Comment by nnra6864** [comment]
> I dunno what happened, but this seems to be fixed

Can confirm.
There are a few other, likely related issues, so I'll open a new bug report soon.
