### ISSUE TITLE
Hyprbars crashing.

### ISSUE THREAD

**Issue by YaroKasear** [hyprwm/hyprland-plugins#168]
I had been using Hyprbars, but it seems to be repeatedly segfaulting for me. It seems to happen especially whenever I resize windows. I made sure to update after this started to make sure it wasn't already a bug that was fixed and no go. 

I am using all git versions here on NixOS via the flake. 

I am trying to attach a log on here but Github seems to be out to lunch or something. It looks like segfaults but the log makes no distinction about what was happening that leads up to the segfault.

**Comment by vaxerski** [comment]
I apologize, missed this one
