### ISSUE TITLE
Remove the <hyprland/...> in border++ include directories to make the instructions from the wiki work

### ISSUE THREAD

**Issue by MathisP75** [hyprwm/hyprland-plugins#17]

**Comment by vaxerski** [comment]
The issue is with our migration to global headers, should update the wiki.

**Comment by MathisP75** [comment]
Ah, makes sense

**Comment by vaxerski** [comment]
blocked by https://github.com/hyprwm/Hyprland/pull/2201

**Comment by vaxerski** [comment]
should be fixed and the wiki should be still valid, but the env is redundant now. I'll edit it.
