### ISSUE TITLE
hyprexpo: How can i contribute?

### ISSUE THREAD

**Issue by leonnelc** [hyprwm/hyprland-plugins#170]
So i really like the hyprexpo plugin and i would like to make some contributions to it like adding a config option for the touchpad gesture fingers instead of a hardcoded value (seems easy enough to start with), adding an option to hide empty workspaces in the overview and maybe other things but i have no clue where to start learning how to do that (i do have a basic level of c++).

I just wanted to ask if someone could provide some documentation or guides to get started

**Comment by vaxerski** [comment]
https://wiki.hyprland.org/Plugins/Development/Getting-Started/

the issues tab is not a programming help forum, please direct those to our discord / matrix / google / reddit. Let's keep this tab for _issues_
