### ISSUE TITLE
Missing git tags for flakes inputs

### ISSUE THREAD

**Issue by dafitt** [hyprwm/hyprland-plugins#178]
New issue to not disturb #177:

> @dafitt:
> 
> > flake.nix inputs (versions i am using):
> > 
> > ```
> > hyprland = { url = "github:hyprwm/Hyprland/tags/v0.40.0"; inputs.nixpkgs.follows = "nixpkgs"; };
> > hyprland-plugins = { url = "github:hyprwm/hyprland-plugins"; inputs.hyprland.follows = "hyprland"; };
> > ```
> 
>   
> @fufexan:
> 
> > @dafitt perhaps hyprland-plugins has a newer version that no longer works with hyprland 0.40, since hyprland-plugins main follows Hyprland's main branch.

I would like to keep using the stable version of Hyprland (because its my daily driver). Is there instead a way to pin hyprland-plugins to v0.40.0? This would be possible with a tag, but hyprland-plugins does not have any tags. Maybe add those?

**Comment by fufexan** [comment]
dcbdc9a08d1df753d6799bab823486f1fff5b8e6 should work, as it's the next commit after the 0.40.0 release.
We'll try to cut tags starting with the next release, right @vaxerski?

**Comment by vaxerski** [comment]
cut tags?

**Comment by fufexan** [comment]
Yeah, like a release but without artifacts. Or you can also make releases if you want.

**Comment by vaxerski** [comment]
I dont understand

**Comment by dafitt** [comment]
https://git-scm.com/book/en/v2/Git-Basics-Tagging

GitHub releases automatically create a tag with the same name as the release. You can see them in your https://github.com/hyprwm/Hyprland/tags, for example. It's just a “tag” on a particular commit.

If you don't want to make a release on Github, you could do it via:

```shell
git tag v0.40.0 dcbdc9a

git push origin v0.40.0
# or
git push origin --tags
```

**Comment by vaxerski** [comment]
oh now I get it, why "cut", "cut" means "remove" tf fufexan.

Anyways why not reset to the pinned commit in hyprpm.toml?

**Comment by dafitt** [comment]
Yes thats certainly possible via url `github:hyprwm/hyprland-plugins/dcbdc9a`. But with semantic versioning we on NixOS could then use more automated tools like https://github.com/snowfallorg/thaw.

**Comment by fufexan** [comment]
> oh now I get it, why "cut", "cut" means "remove" tf fufexan.
> 
> Anyways why not reset to the pinned commit in hyprpm.toml?

idk I, saw the terminology somewhere.
