### ISSUE TITLE
Help for hyprland plugin dev

### ISSUE THREAD

**Issue by RafayAhmad7548** [hyprwm/hyprland-plugins#179]
i was making a plugin, but i ran into issues and i cant find much detailed documentation. basically i am stuck on how to get a pointer to the current wlr_keyboard in the init fuction so i can setup some keylisteners, also with another plugin i was setting up a eventlistner for activewindow changem i got a PHLWINDOW from the void* data in the eventlistner callback but i dont know how to use the PHILWINDOW for literally anything. any help would be appreciated

**Comment by vaxerski** [comment]
the issues page is not a help forum. Go to the discord for that.

This repo has more than enough examples of how to use a window ptr

Current keyboard is `g_pSeatManager->keyboard`

**Comment by RafayAhmad7548** [comment]
Thank you,  i am sorry for asking here
