### ISSUE TITLE
Invalid dispatcher, requested hyprexpo:expo does not exist (bind.conf)

### ISSUE THREAD

**Issue by jude7733** [hyprwm/hyprland-plugins#181]
I am experiencing an error when trying to use the hyprpm-expo plugin. The Hyprland error message is:
**Invalid dispatcher, requested hyprexpo:expo does not exist**
Error source is from line:
```
bind = SUPER, TAB, hyprexpo:expo, toggle
```

*The error started showing up after updating hyprland to 0.41,(worked perfect in 0.40)*

### $ hyprctl version
Hyprland, built from branch  at commit ea2501d4556f84d3de86a4ae2f4b22a474555b9f  (props: bump version to 0.41.0).
Date: Mon Jun 10 14:23:06 2024
Tag: v0.41.0, commits: 4794

### $ hyprpm list
 → Repository hyprland-plugins:
  │ Plugin borders-plus-plus
  └─ enabled: false
  │ Plugin csgo-vulkan-fix
  └─ enabled: false
  │ Plugin hyprbars
  └─ enabled: true
  │ Plugin hyprexpo
  └─ enabled: true
  │ Plugin hyprtrails
  └─ enabled: false
  │ Plugin hyprwinwrap
  └─ enabled: false

**Comment by vaxerski** [comment]
verify the plugin is successfully loaded with `hyprctl plugin list`. Hyprpm might report true but the plugin could have failed to initialize.

**Comment by jude7733** [comment]
Thank you for your reply, the recent **hyprpm update** *solved* the issue.
