### ISSUE TITLE
hyprexpo: Invalid dispatcher, requested "hyprexpo:expo" does not exist

### ISSUE THREAD

**Issue by truemaker** [hyprwm/hyprland-plugins#184]
`hyprpm list` shows that the plugin is loaded.

Hyprland version: 0.41.0

**Comment by truemaker** [comment]
`hyprctl plugin list` says no plugins are loaded.

**Comment by vaxerski** [comment]
then hyprexpo failed to load

**Comment by truemaker** [comment]
It is now fixed (for some reason)
