### ISSUE TITLE
Hyprwinwrap causes apps to crash Hyprland

### ISSUE THREAD

**Issue by nnra6864** [hyprwm/hyprland-plugins#185]
I am on Arch, Hyprland Git and Hyprpm updated properly.
If I enable Hyprwinwrap and open an app such as kitty or telegram, the entire Hyprland session crashes.
Here's the latest crash log I got:
[hyprlandCrashReport7477.txt](https://github.com/user-attachments/files/15857264/hyprlandCrashReport7477.txt)
Here's a plugin related part of my config too:
```
plugin {
    hyprwinwrap {
	class = GLava
    }
}
```

**Comment by NyxTrail** [comment]
Can confirm similar crashes with hyprwinwrap enabled and launching kitty.
[hyprlandCrashReport333745.txt](https://github.com/user-attachments/files/15858130/hyprlandCrashReport333745.txt)

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/user-attachments/files/15859302/patch.txt)
try this

**Comment by nnra6864** [comment]
> [patch.txt](https://github.com/user-attachments/files/15859302/patch.txt) try this

I added the if check you sent and now it just crashes as soon as I enable the plugin.
Here's the latest crash report:
[hyprlandCrashReport103825.txt](https://github.com/user-attachments/files/15859995/hyprlandCrashReport103825.txt)
As well as the function I changed(in case I missed something):
```
void onCommitSubsurface(CSubsurface* thisptr) {
	if (!thisptr->m_pWLSurface) {
        ((origCommitSubsurface)subsurfaceHook->m_pOriginal)(thisptr);
        return;
    }

    const auto PWINDOW = thisptr->m_pWLSurface->getWindow();

    if (!PWINDOW || std::find_if(bgWindows.begin(), bgWindows.end(), [PWINDOW](const auto& ref) { return ref.lock() == PWINDOW; }) == bgWindows.end()) {
        ((origCommitSubsurface)subsurfaceHook->m_pOriginal)(thisptr);
        return;
    }

    // cant use setHidden cuz that sends suspended and shit too that would be laggy
    PWINDOW->m_bHidden = false;

    ((origCommitSubsurface)subsurfaceHook->m_pOriginal)(thisptr);
    if (const auto MON = g_pCompositor->getMonitorFromID(PWINDOW->m_iMonitorID); MON)
        g_pHyprOpenGL->markBlurDirtyForMonitor(MON);

    PWINDOW->m_bHidden = true;
}
```

**Comment by jDmacD** [comment]
same on nixos / home-manager

[crash report](https://gist.github.com/jDmacD/b3525093aa63d6d9b6ecbb6364376311)

**Comment by TKasperczyk** [comment]
The crash occurs when you try to access `thisptr->m_pWLSurface`, even when doing stuff like:

```
if (!thisptr) {
    // ...
}
// The following check will cause a crash
if (!thisptr->m_pWLSurface) {
    //...
}
```

Interestingly, simply ignoring the body of this function, i.e. returning immediately, makes the plugin work just fine:

```
void onCommitSubsurface(CSubsurface* thisptr) {
    return;
}
```

Tested with the standard example of kitty + cava.

**Comment by nnra6864** [comment]
> The crash occurs when you try to access `thisptr->m_pWLSurface`, even when doing stuff like:
> 
> ```
> if (!thisptr) {
>     // ...
> }
> // The following check will cause a crash
> if (!thisptr->m_pWLSurface) {
>     //...
> }
> ```
> 
> Interestingly, simply ignoring the body of this function, i.e. returning immediately, makes the plugin work just fine:
> 
> ```
> void onCommitSubsurface(CSubsurface* thisptr) {
>     return;
> }
> ```
> 
> Tested with the standard example of kitty + cava.

Thanks a ton for this!
I just tested it on my end with GLava and it works flawlessly!

**Comment by atikiNBTW** [comment]
While I was experimenting with this, I found out that it is hooking the wrong function. E.g. instead of calling CSubsurface::onCommit it is calling CTextInput::onCommit, so simply changing the line 156 to `subsurfaceHook = HyprlandAPI::createFunctionHook(PHANDLE, fn.address, (void*)&onCommitSubsurface);` fixes it! Can anyone create a pr to fix this?

**Comment by atikiNBTW** [comment]
I'm also looking into making tiled windows xray'able so the wallpaper will be shown: 

https://github.com/user-attachments/assets/646f7d55-0590-47ab-8811-015910fc704e

**Comment by nnra6864** [comment]
> I'm also looking into making tiled windows xray'able so the wallpaper will be shown:
> file.mp4

I discussed this in another issue.
While it's a workaround, it works:
#167

**Comment by dotaxis** [comment]
> While I was experimenting with this, I found out that it is hooking the wrong function. Instead of hooking CSubsurface::onCommit it is hooking CTextInput::onCommit, so simply changing the line 156 to `subsurfaceHook = HyprlandAPI::createFunctionHook(PHANDLE, fn.address, (void*)&onCommitSubsurface);` fixes it! Can anyone create a pr to fix this?

This does indeed fix the crashing but cava doesn't seem to properly update when on the background layer. Can anyone confirm if this is a me issue?
