### ISSUE TITLE
Failure building hyprland plugins due to 'm_sSpecialRenderData' dependency missing 

### ISSUE THREAD

**Issue by axelyamel01** [hyprwm/hyprland-plugins#199]
I posted this issue in the [hyprland repo](https://github.com/hyprwm/Hyprland/issues/6854). The main problem is after the commit  [a443902abca6549839910720b80bd01faf10f387](https://github.com/hyprwm/Hyprland/commit/a443902abca6549839910720b80bd01faf10f387) in the hyprland repo, the plugins can't be built. The process fails with the following message:

```
$ hyprpm update -f -v

...

barDeco.cpp:392:19: error: ‘class CWindow’ has no member named ‘m_sSpecialRenderData’
  392 |     if (!PWINDOW->m_sSpecialRenderData.decorate)
      |                   ^~~~~~~~~~~~~~~~~~~~
```

According to the reply in the post, `m_sAdditionalConfigData` and `m_sSpecialRenderData` need to be replaced with `m_sWindowData`. 

Complete failure log: [hyprpm-fail.log](https://github.com/user-attachments/files/16200865/hyprpm-fail.log)

**Comment by fufexan** [comment]
Fixed in 928164d.

**Comment by vaxerski** [comment]
thanks fuf

**Comment by fufexan** [comment]
anytime
