### ISSUE TITLE
Hyprwinwrap behaves differently if a window is tiled

### ISSUE THREAD

**Issue by nnra6864** [hyprwm/hyprland-plugins#212]
Similar issues reported are #167, #197 and #91.
To sum it up, when using `decoration:blur:ignore_opacity = true`, hyprwinwrap isn't rendered behind tiled windows.
I am suspecting this to be a hyprland issue rather than hyprwinwrap issue because window being tiled or not causes this.
Interesting thing is that if you make the window float and then fullscreen/maximize it with either of these binds(and possibly others):
`bind = $mainMod, F, fullscreen`
`bind = $mainMod ALT, F, fullscreenstate, 1`
hyprwinwrap gets rendered properly, as shown here:
### Tiled
![tiled](https://github.com/user-attachments/assets/066e9fac-0e8b-4f37-a4c5-4ddec41fb942)
### Floating
![floating](https://github.com/user-attachments/assets/862ccc54-0515-47ad-985d-1a5ddde9baac)
### Maximized
![maximized](https://github.com/user-attachments/assets/40b44025-975f-45fe-96e5-ec93e8eb0070)
### Fullscreen
![fullscreen](https://github.com/user-attachments/assets/443c51d8-576a-4eaa-a2ef-65f452a3b024)
### Tiled with `decoration:blur:ignore_opacity = false`
![image](https://github.com/user-attachments/assets/bda63e34-fe43-4ddb-be9e-2ab5104e93a2)

I would like to be of more use but I am not familiar with the hyprland codebase so hopefully somebody experienced will be able to fix this.

## EDIT
I found a really interesting thing...
It seems to behave properly when used on a special workspace o_0
![image](https://github.com/user-attachments/assets/33f9e22f-4de7-418b-8f80-cc078a7e95d5)

**Comment by firashacker** [comment]
i have this same issue and i need fix

**Comment by nnra6864** [comment]
Huge find!
This is directly tied to the following blur setting: `new_optimizations = true`!
I genuinely have no clue how I never tried setting it to `false` before...
Disabling it straight up fixes the issue fully!
Yeah, performance is supposedly worse but at least it behaves properly :/
Hope this thread is of help to any future users and gives Vaxry an idea of what could be causing the issue.

**Comment by nnra6864** [comment]
Ok, I went through the hyprland codebase and I have an assumption as to why these optimizations block the hyprwinwrap rendering.
From my understanding, new optimizations are basically avoiding re-rendering of non dirty windows(windows with no changes), which results in hyprwinwrap not being displayed through them since nothing's updated(I could be very wrong about this).
It also explains why it's working with floating and special workspace windows, because a window doesn't qualify for these optimizations if it's floating or on a special workspace, as can be seen [here](https://github.com/hyprwm/Hyprland/blob/a8ff3a452c1c445d24bdd9e7e4fcd66c8ef2a147/src/render/OpenGL.cpp#L2027).
If you are using hyprwinwrap, you are better off just disabling these new optimizations because blur has to be constantly re-rendered anyways.
I won't close the issue yet because I am awaiting a response in the hyprland discord server since I don't have enough knowledge to truly mark this as a solution/intended behaviour.
