### ISSUE TITLE
Corners with Hyprbar Plugin

### ISSUE THREAD

**Issue by jncsotk30** [hyprwm/hyprland-plugins#219]
Hello, this isn't an issue per se, but an "improvement" / UI change request. If using the hyprbars plugin, would it be possible to unset the top left / right corner radius of the application window? It looks kind of redundant combined with the titlebar both being rounded. If not, no worries. 

![21:15:48-2024-09-01-area](https://github.com/user-attachments/assets/96fee96d-e65e-4831-9320-2992373d4894)

**Comment by vaxerski** [comment]
the hyprland renderer doesnt support that atm

**Comment by jncsotk30** [comment]
> the hyprland renderer doesnt support that atm

Ok, thanks. If there’s any potential in the future, would love to see it. I’m not savvy enough with the code to do myself currently.
