### ISSUE TITLE
hyprtrails failing to build

### ISSUE THREAD

**Issue by PolarT-py** [hyprwm/hyprland-plugins#228]
my life ruined
![image](https://github.com/user-attachments/assets/32c59c3f-6b34-4460-ab6f-83fd683c4ef1)

**Comment by fufexan** [comment]
Hyprland version?

**Comment by vaxerski** [comment]
seems to build for me, this might be that I forgot to add a 0.43.0 pin and there has been a breaking change since, try now

**Comment by PolarT-py** [comment]
lets go it works now, thanks so much!
