### ISSUE TITLE
Bug: Hyprexpo dispatcher kills hyprland session

### ISSUE THREAD

**Issue by CarloCattano** [hyprwm/hyprland-plugins#239]
Since yesterday, calling the dispatcher kills my wayland session back to sddm

```bind = $Mod, w , exec , hyprctl dispatch hyprexpo:expo toggle```

```
Hyprland 0.44.0 built from branch main at commit cd0d0491261728260de3d1aff150e1b6c05f9e86  (flake.lock: update xdph).
Date: Sun Nov 3 17:43:08 2024
Tag: v0.44.0-108-gcd0d0491, commits: 5407
built against aquamarine 0.4.3
```

```
Linux arch 6.12.0-rc4-1-mainline #1 SMP PREEMPT_DYNAMIC Tue, 22 Oct 2024 07:33:32 +0000 x86_64 GNU/Linux
```

**Comment by parliamentbomber** [comment]
what version of hyprexpo? latest?

**Comment by CarloCattano** [comment]
latest I can get from hyprpm.
Its interesting now it just tells me invalid dispatcher
```hyprctl dispatch hyprexpo:expo
Invalid dispatcher```

**Comment by CarloCattano** [comment]
Crash is again there, I will try to setup debugging in Hyprland and see if I can spot what causes this

**Comment by CarloCattano** [comment]
There is an abort signal somehow
```
Nov 04 10:12:31 arch systemd-coredump[5384]: Process 5052 (Hyprland) of user 1000 terminated abnormally with signal 6/ABRT, processing...
```

And then a coredump
```
Nov 04 10:12:31 arch systemd-coredump[5385]: [🡕] Process 5052 (Hyprland) of user 1000 dumped core.
```

**Comment by CarloCattano** [comment]
probably since this commit but cant really be sure until I compile it myself 
https://github.com/hyprwm/hyprland-plugins/commit/c347d8ad9b80370d573e5a01b2e8bf10e6d0dbe5#diff-d46c99b6d6cc14ffdbf7e49c852f46516dd979980e68ac51ef16c415068a26bb

It surely happened less than 48h ago
