### ISSUE TITLE
Hyprpm wont update

### ISSUE THREAD

**Issue by tomasvilio** [hyprwm/hyprland-plugins#244]
hi this is my second issue because for some reason you guys closed my issue without it being solved
Again i have a problem when trying to install a plugin and it tells me to update hyprpm, but when i try that, it says i need hyprutils which is already installed. 
pls dont close my issue again without it being solved, i want help not a guy who just told me that the answer was obvious and that i needed hyprutils, which i already had, and closed my issue without it being solved or doing anything else.

here are the command outputs

first command:  yay -S hyprutils        

Sync Explicit (1): hyprutils-0.2.4-1
[sudo] password for vaiena: 
warning: hyprutils-0.2.4-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Package (1)      Old Version  New Version  Net Change

extra/hyprutils  0.2.4-1      0.2.4-1        0.00 MiB

Total Installed Size:  0.21 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] Y
(1/1) checking keys in keyring                                                                                   [-------------------------------------------------------------------] 100%
(1/1) checking package integrity                                                                                 [-------------------------------------------------------------------] 100%
(1/1) loading package files                                                                                      [-------------------------------------------------------------------] 100%
(1/1) checking for file conflicts                                                                                [-------------------------------------------------------------------] 100%
(1/1) checking available disk space                                                                              [-------------------------------------------------------------------] 100%
:: Processing package changes...
(1/1) reinstalling hyprutils                                                                                     [-------------------------------------------------------------------] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...

second command: hyprpm update --no-shallow 

! Cloning https://github.com/hyprwm/Hyprland, this might take a moment.                                                                                                                    
✔ Hyprland cloned                                                                                                                                                                          
✔ checked out to running ver                                                                                                                                                               
! configuring Hyprland                                                                                                                                                                     
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╍━━━━━━━━━━━━━━━━━━━  3 / 5  Building Hyprland                                                                                                              
✖ Could not configure the hyprland source, cmake complained:
-- The C compiler identification is GNU 14.2.1
-- The CXX compiler identification is GNU 14.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Gathering git info
-- Found PkgConfig: /home/linuxbrew/.linuxbrew/bin/pkg-config (found version "0.29.2")
-- Checking for module 'udis86>=1.7.2'
--   No package 'udis86' found
-- Found Python3: /home/linuxbrew/.linuxbrew/bin/python3.13 (found version "3.13.0") found components: Interpreter
Building itab.c/itab.h...
-- udis86 dependency not found, falling back to subproject
Package wayland-protocols was not found in the pkg-config search path.
Perhaps you should add the directory containing `wayland-protocols.pc'
to the PKG_CONFIG_PATH environment variable
No package 'wayland-protocols' found
-- Found wayland-protocols at 
Package wayland-scanner was not found in the pkg-config search path.
Perhaps you should add the directory containing `wayland-scanner.pc'
to the PKG_CONFIG_PATH environment variable
No package 'wayland-scanner' found
-- Found wayland-scanner pkgdatadir at 
-- Configuring Hyprland in Release with CMake
-- Checking deps...
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Found OpenGL: /usr/lib/libOpenGL.so  found components: GLES3
-- Checking for module 'hyprutils>=0.2.4'
--   No package 'hyprutils' found
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:645 (message):
  The following required packages were not found:

   - hyprutils>=0.2.4

Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPkgConfig.cmake:873 (_pkg_check_modules_internal)
  CMakeLists.txt:104 (pkg_check_modules)

This likely means that you are missing the above dependencies or they are out of date.

**Comment by tomasvilio** [comment]
dont close my issue pls

**Comment by vaxerski** [comment]
No, because the problem is with your system and not hyprland. It works for everyone else.

If you use arch, it is expected of **you** to know your system and be able to deal with your issues.

You have various other issues too: `No package 'wayland-scanner' found` for example.

the hyprutils package could also be broken on arch, build it from source.

**Comment by tomasvilio** [comment]
i tried
but it does not make any sence that you provide me absolutly no help bro

**Comment by vaxerski** [comment]
I don't know how many times I have to repeat this.

_I do not and never have used Fedora_
