### ISSUE TITLE
[HYPRBARS] Recent update broke rgba button backgrounds

### ISSUE THREAD

**Issue by RambilE** [hyprwm/hyprland-plugins#260]
Title.
The error is: "Config error in file /path/to/config at line n: var2 is not a valid number"

**Comment by vaxerski** [comment]
post your config maybe?

**Comment by RambilE** [comment]
THIS \/ works fine
hyprbars-button = rgb(000000), 17, , hyprctl dispatch killactive
Before i updated, something like this \/ would work
hyprbars-button = rgba(25,25,25,0), 17, , hyprctl dispatch killactive

What's strange is that bar can be rgba, but buttons can't.

**Comment by vaxerski** [comment]
that's probably because we use `,` as a delimiter so it gets cut into `rgba(25` as color and that's not valid.

Just use the non-comma version `rgba(19191900)`

**Comment by RambilE** [comment]
oh, thank you, it now works. dk how it have worked before
