### ISSUE TITLE
[BORDERS-PLUS-PLUS] Color not displaying correctly

### ISSUE THREAD

**Issue by kylfp** [hyprwm/hyprland-plugins#261]
Since the most recent update the borders-plus-plus plugin has been unable to display colors correctly. The supplied screenshot shows the transparent outer border. The given color should match the hyprbar also shown in the screenshot. I have tried multiple colors and all display completely transparent.

```
  borders-plus-plus {
    add_borders = 1
    col.border_1 = rgb(282c34)
    border_size_1 = 10
    natural_rounding = yes
  }
```
![Screenshot](https://github.com/user-attachments/assets/c0545877-29c0-44f1-bd68-9ebeed7f383e)

**Comment by vaxerski** [comment]
yep fixed
