### ISSUE TITLE
 hyprbar: hyprland crashes

### ISSUE THREAD

**Issue by shadowelite-sec** [hyprwm/hyprland-plugins#27]
Hyprland is crashing when I execute VS Code because of Hyprbar.

![20230512_21h51m52s_grim](https://github.com/hyprwm/hyprland-plugins/assets/54718375/ee273c44-731a-41c8-9f19-ba785e806731)

only when i click any of this top menu (file , edit , etc)
 
 How can I fix this issue?

[hyprlandCrashReport504.txt](https://github.com/hyprwm/hyprland-plugins/files/11466059/hyprlandCrashReport504.txt)

**Comment by vaxerski** [comment]
check with 63450e70f2e1d74964e0121e0c865b1d48a2cae3, should be fixed

**Comment by shadowelite-sec** [comment]
### Yes, thanks, it's working now.


But there is one issue: the hyperbars are also applying to VSCode menu windows

![20230514_20h16m27s_grim](https://github.com/hyprwm/hyprland-plugins/assets/54718375/94eea806-cb85-44b7-98e9-a0d6356b036c)

And the window class and tile of those menu windows are empty

![20230514_20h31m37s_grim](https://github.com/hyprwm/hyprland-plugins/assets/54718375/6314f753-9d43-4329-ab15-1fb338da6b8b)

**Comment by vaxerski** [comment]
launch vscode in native wayland and not xwayland to fix that in the meantime

**Comment by shadowelite-sec** [comment]
> launch vscode in native wayland and not xwayland to fix that in the meantime

Thanks

**Comment by vaxerski** [comment]
fixed in e368bd15e4bfd560baa9333ad47415340c563458
