### ISSUE TITLE
Feature Request - Hyprbars: Show only on floating windows

### ISSUE THREAD

**Issue by Kvn0l** [hyprwm/hyprland-plugins#28]
An option to only show title bars on floating windows would be a cool addition to manage floating windows while keeping the tiled ones unchanged.

**Comment by snehrbass** [comment]
I have already implemented a rough working version of this but needs some polishing before being merged, it meets my needs so I've been lazy. https://github.com/snehrbass/sn-hyprland-plugins/tree/sn-win-filter/hyprbars

**Comment by Kvn0l** [comment]
> I have already implemented a rough working version of this but needs some polishing before being merged, it meets my needs so I've been lazy. https://github.com/snehrbass/sn-hyprland-plugins/tree/sn-win-filter/hyprbars

Nice! I'm gonna try right away

**Comment by Kvn0l** [comment]
> I have already implemented a rough working version of this but needs some polishing before being merged, it meets my needs so I've been lazy. https://github.com/snehrbass/sn-hyprland-plugins/tree/sn-win-filter/hyprbars

I've noticed a weird behavior that u probably already know:
When window is tiled and bar's hidden, clicking & dragging on the top border acts as if the titlebar is there and drag the window around.

**Comment by mpnordland** [comment]
@nehrbash is this closer to being merged?

**Comment by AdamSitar** [comment]
Essential feature, I hope this gets merged soon

**Comment by etrigan63** [comment]
By extension, can the inverse of this be applied as well? No hyprbar on floating windows so that popups, splashscreens and notifications don't have them?

**Comment by TheFrankyDoll** [comment]
For those still looking, now writing `windowrulev2 = plugin:hyprbars:nobar, float:0` in your configuration does exactly what the original feature request asked for.

**Comment by x70b1** [comment]
Thats not working. The rule should be `windowrulev2 = plugin:hyprbars:nobar,floating:0`

**Comment by cicero-violate** [comment]
> For those still looking, now writing `windowrulev2 = plugin:hyprbars:nobar, floating:0` in your configuration does exactly what the original feature request asked for.

thank you! you got me going in the right direction
