### ISSUE TITLE
Bug: hyprbars status is abnormal  

### ISSUE THREAD

**Issue by lisuke** [hyprwm/hyprland-plugins#3]
When I use the hyprbars plugin, dragging window's content often automatically enters the drag mode, like dragging hyprbars.

**Comment by vaxerski** [comment]
can you find a way to reproduce this?

**Comment by lisuke** [comment]
> can you find a way to reproduce this?

After opening it, dragging the selected text within the open program window will trigger window dragging. 

This problem continues to occur in my system, and I don't know if it can be replicated by others.

Till now, I don't know what I should do to solve this bug?

**Comment by lisuke** [comment]
Recently, it has been found that there should be no obvious pattern when entering this state.

It is more obvious that when a form enters this state:

1. This form will not return to its original layout.
2. When the mouse moves past other forms, there is a high probability that the program will also enter this state.
