### ISSUE TITLE
Hyprbars leaving trails behind when dragged

### ISSUE THREAD

**Issue by ardishco-the-great** [hyprwm/hyprland-plugins#32]
I don't exactly know how I can put this into words, so I will leave a video and explain how to reproduce

reproduction:

1. run ``git clone --recursive https://github.com/hyprwm/hyprland-plugins/ && cd hyprland-plugins && hyprbars && make``
2. Load plugin
3. Try dragging it around, see trails of hyprbars around
(See in video)

I would like to add that this behavior is also observed when the window is floating, it does not vary.

**Comment by ardishco-the-great** [comment]
oops, forgot to attach the video.

Here: https://streamable.com/qk2yzg

**Comment by vaxerski** [comment]
check with 16dc2927bdfb1b133fd682fa0b451155918a07d9

**Comment by ardishco-the-great** [comment]
recloned, recompiled and the issue still persists. If there is anything I can do to help like send logs I would be more than happy to do so.

**Comment by vaxerski** [comment]
it definitely looks wrong.

**Comment by kescherCode** [comment]
This issue has disappeared. It used to happen, but no longer does.
