### ISSUE TITLE
[csgo-vulkan-fix] Plugin breaks mouse clicking on latest git version of Hyprland

### ISSUE THREAD

**Issue by Guanran928** [hyprwm/hyprland-plugins#35]
`csgo-vulkan-fix` plugin breaks mouse clicking on latest git version of Hyprland (hyprland-nvidia-git)

Video:
https://github.com/hyprwm/hyprland-plugins/assets/68757440/65320352-4702-48bf-98e6-406c9faa5305

`hyprctl version`
```
Hyprland, built from branch main at commit 51cda87fe47efec25265b3b9f6bebf9a0882aa08 dirty (hyprctl: rerender on cursor_zoom_factor dynamic calls).
Tag: v0.27.2-64-g51cda87f

flags: (if any)

```

Config file
```
   1   │ # need to be absolute path
   2   │ plugin = $HOME/.config/hypr/plugins/csgo-vulkan-fix.so
   3   │ #plugin = $HOME/.config/hypr/plugins/hyprfocus.so
   4   │
   5   │ plugin {
   6   │   csgo-vulkan-fix {
   7   │         res_w = 1440
   8   │         res_h = 1080
   9   │     }
 10   │ }
```

The plugin is built a while ago, but I am unable to clone the repo to re-build due to some internet issues, will attempt later.

**Comment by vaxerski** [comment]
you are unable to clone but you can upload a video?

Please recompile. Every hyprland version change (even from one commit to another) requires plugins to be recompiled

**Comment by Guanran928** [comment]
> you are unable to clone but you can upload a video?
> 
> Please recompile. Every hyprland version change (even from one commit to another) requires plugins to be recompiled

(I was getting ~10kb/s download speed while cloning the repo, not sure why)

Yes, re-compiling worked, thank you for the tip.
