### ISSUE TITLE
borders-plus-plus thickness

### ISSUE THREAD

**Issue by exoess** [hyprwm/hyprland-plugins#40]
Why can't you adjust the thickness of the additional borders?

**Comment by vaxerski** [comment]
because it's not implemented?

**Comment by vaxerski** [comment]
2ae696398a532a8a017cc35f7dfbada7a8ccbdf4

**Comment by maotseantonio** [comment]
hey in nixos borders plus plus plugin didnt work. And hyprpm is didnt work in nixos. Plz make hyprpm usable in nixos

**Comment by fufexan** [comment]
@maotseantonio have you read the wiki? Hyprpm is not supported on NixOS. Use `wayland.windowManager.hyprland.plugins`.

**Comment by maotseantonio** [comment]
yeah I read the wiki and follow the wiki. but I am facing with version mismatching error. I install hyprland with flake and hyprland plugin follow the hyprland but I install the plugin version mismatching is always occur

**Comment by maotseantonio** [comment]
and I check the version of hyprland and my plugin borders-plus-plus version. my hyprland version is 0.45 and plugin version is 0.44

**Comment by maotseantonio** [comment]
![20241112_145405](https://github.com/user-attachments/assets/5e4dcd7d-9e32-42b8-a172-f2075413bf33)


![20241112_145342](https://github.com/user-attachments/assets/a3384ee3-df15-4bd8-8557-a806075638de)
like this

**Comment by fufexan** [comment]
Plugins should be working with hyprland git. Try doing a `nix flake update` to ensure you're up to date.

**Comment by maotseantonio** [comment]
thanks its work

**Comment by maotseantonio** [comment]
hey in 0.46 borders plus plus plugin didnt shown? in startup shown the load plugin but cant see the borders
