### ISSUE TITLE
plugin(borders-plus-plus) can't compile 

### ISSUE THREAD

**Issue by DreamMaoMao** [hyprwm/hyprland-plugins#41]
![image](https://github.com/hyprwm/hyprland-plugins/assets/30348075/d5e759ad-a1ed-45c4-9670-745c67f5e5c7)

and another plugin() can compile:
![image](https://github.com/hyprwm/hyprland-plugins/assets/30348075/7de04af6-f502-4882-b1dd-82893e75795d)

example plugin also can't compile:
![image](https://github.com/hyprwm/hyprland-plugins/assets/30348075/07d90dfb-2554-4cb2-bde4-891775f042a5)

**Comment by vaxerski** [comment]
all plugins fixed
