### ISSUE TITLE
[csgo-vulkan-fix] Failure in initilization (hook failed)!

### ISSUE THREAD

**Issue by monkhaze** [hyprwm/hyprland-plugins#42]
I can't seem to get the plugin to load.

Compiled hyprland from github master with: `sudo make install`
Compiled hyprland-plugins csgo-vulkan-fix from github master with: `make all`

I tried running hyprland with strace and looking through the logs but couldn't find anything.

### Problem
```
[malts@rei csgo-vulkan-fix]$ hyprctl plugin load /home/malts/src/hyprland-plugins/csgo-vulkan-fix/csgo-vulkan-fix.so 
ok
```
![20230928_02h35m05s_grim](https://github.com/hyprwm/hyprland-plugins/assets/6921039/7cd11392-2a80-4e2d-8548-ea456b1fe040)

Same thing seems to happen if I define the plugin in hyprland.conf like so:
```
plugin = /home/malts/.config/hypr/csgo-vulkan-fix.so

plugin {
    csgo-vulkan-fix {
        res_w = 1024
        res_h = 768
    }
}
```

**Comment by vaxerski** [comment]
plugin requires AMD64 (aka x86-64)

Are you perhaps on ARM?

**Comment by monkhaze** [comment]
@vaxerski AMD64, Ryzen 7 3700X

**Comment by vaxerski** [comment]
OOOOPS, fixed. 35ca302ff78e4c8b3305967ca53321577b8b50ea

**Comment by monkhaze** [comment]
@vaxerski Wonderful, that fixed it! Thanks :+1:

**Comment by 3ri4nG0ld** [comment]
I am having this problem with the latest version.

```
└─$ hyprpm -v reload
[v] version returned: Hyprland, built from branch main at commit a60c7283e677ed81a466d1c0c864c8a05e192cac  (xwayland: verify new xsurf is valid in prop reads).
Date: Wed May 29 09:34:25 2024
Tag: v0.40.0-144-ga60c7283, commits: 4750

flags: (if any)


[v] parsed commit a60c7283e677ed81a466d1c0c864c8a05e192cac at branch main on Wed May 29 09:34:25 2024, commits 4750
✔ Ensuring plugin load state
✔ Loaded csgo-vulkan-fix
✔ Plugin load state ensured
```
