### ISSUE TITLE
Hyprbars: Fails to build on NixOS

### ISSUE THREAD

**Issue by scotabroad** [hyprwm/hyprland-plugins#47]
I get these build errors when trying to add hyprbars to my NixOS config [log.txt](https://github.com/hyprwm/hyprland-plugins/files/13210458/log.txt)

For reference, I use `wayland.windowManager.hyprland.package = inputs.hyprland.packages.${pkgs.system}.hyprland;` in my Home-Manager config and `programs.hyprland.package = inputs.hyprland.packages.${pkgs.system}.hyprland;` in my nix config.

**Comment by scotabroad** [comment]
Also, my `flake.lock` file has been updated to the latest commits from Hyprland and Hyprland-Plugins.

**Comment by vaxerski** [comment]
@fufexan chan for nix

**Comment by fufexan** [comment]
Looks like a mismatch between Hyprland and the plugin. What I do to keep them in sync is add the plugin [like this](https://github.com/fufexan/dotfiles/blob/main/home/wayland/hyprland/default.nix#L21) and override `hyprland-plugins`' `hyprland` input [like this](https://github.com/fufexan/dotfiles/blob/main/flake.nix#L90-L93).
