### ISSUE TITLE
BUG: Hyprbars does nothing

### ISSUE THREAD

**Issue by Froggo8311** [hyprwm/hyprland-plugins#5]
I'm trying to run hyprbars, but it doesn't do anything.
```bash
$ hyprctl plugin load $(pwd)/hyprbars.so
ok
$ 
```
There's a little banner in the top-right corner, `[hyprbar] Initialized successfully!`

No window decoration is ever created.
I could just be dumb, but I don't think anything happened.
![2023-04-04-225910_screenshot](https://user-images.githubusercontent.com/92762044/229977813-37e3774e-406e-4831-a36e-c8861ca9150b.png)

**Comment by vaxerski** [comment]
had the same, forgot my sources were mismatched with the sources hyprland was built from.

**Comment by Froggo8311** [comment]
That's the only issue? Cool
