### ISSUE TITLE
[Feature] Hyprwinwrap: Pass mouse position

### ISSUE THREAD

**Issue by Arjun31415** [hyprwm/hyprland-plugins#52]
Feature Request to pass in mouse movements to the floating window created by the plugin. 
This would make it possible to set a webGL webpage as background and interact with it.
For ex : [fluid-simulation](https://michaelbrusegard.github.io/WebGL-Fluid-Enhanced/).

**Comment by T-Crypt** [comment]
@Arjun31415 

How are we supposed to pass something to the Background? the example provided still opens a window when launching cava.

**Comment by Arjun31415** [comment]
Yeah makes sense, it would need be focused for the cursor position to be passed to it. Maybe a workaround with `hyprctl cursorpos`, but that would be out of scope of this plugin imo
