### ISSUE TITLE
Hyprbars issues with shadows since new border changes in Hyprland

### ISSUE THREAD

**Issue by MathisP75** [hyprwm/hyprland-plugins#55]
It seems like the title bar is not wide enough since the borders were made into decorations.

With `bar_part_of_window = true`:

![image](https://github.com/hyprwm/hyprland-plugins/assets/98901170/a1531523-06ae-43fe-acae-21a27c32b04a)
***
With `bar_part_of_window = false`:

![image](https://github.com/hyprwm/hyprland-plugins/assets/98901170/fada7324-0809-4d85-9fcf-b1c0078c38aa)

**Comment by vaxerski** [comment]
hm, hyprbars shouldnt need to calc in borders, it should be done by the deco positioner. Odd. Prolly a bug in the positioner.

**Comment by vaxerski** [comment]
fixed in both https://github.com/hyprwm/Hyprland/commit/8191e635a33ea634846f6458b42685da277f50b5 and 9099c480d84563f3e86548b8f9a4494fd2b11bd1
