### ISSUE TITLE
Hyprbars: add maximum title lenght config option

### ISSUE THREAD

**Issue by MathisP75** [hyprwm/hyprland-plugins#56]
![image](https://github.com/hyprwm/hyprland-plugins/assets/98901170/cc2c7b25-d69f-4e01-b048-90dc050793b3)

**Comment by vaxerski** [comment]
lenght

**Comment by MathisP75** [comment]
Oh yeah, indeed

**Comment by MathisP75** [comment]
Thanks a lot mr. vaxry
