### ISSUE TITLE
Hyprbars: fullscreened windows can be dragged by pressing near the top

### ISSUE THREAD

**Issue by cuddleplush** [hyprwm/hyprland-plugins#57]
If you fullscreen a window with hyprbars, you can still drag it by pressing near the top of the window, even though the bar itself does not appear to be visible. This is especially problematic in games, as shown in the video. From what I can tell, it seems you need to drag on the top-most pixel of the window for this to happen.
Notably, this issue is not present if you have `border_size = 1` or higher (I have 0), However it is present if you have `border_size = 1` AND `bar_precedence_over_border = true`.

https://github.com/hyprwm/hyprland-plugins/assets/68853493/4497b13d-cf57-4e71-b015-212be5e93ec4

Hyprland built from [01e5c59d752d3fe7fa484330fa48e010054b8fa1](https://github.com/hyprwm/Hyprland/commit/01e5c59d752d3fe7fa484330fa48e010054b8fa1)
Hyprbars built from [d4350bfff705c447efe332009fe07f73da187804](https://github.com/hyprwm/hyprland-plugins/commit/d4350bfff705c447efe332009fe07f73da187804)

**Comment by vaxerski** [comment]
I am sorry for this bug :(

**Comment by vaxerski** [comment]
check with af229e6aee2b1f3c005529862b17c2e2a3d6c8c7

**Comment by cuddleplush** [comment]
> check with [af229e6](https://github.com/hyprwm/hyprland-plugins/commit/af229e6aee2b1f3c005529862b17c2e2a3d6c8c7)

Seems to be fixed, thank you!
