### ISSUE TITLE
Hyprbars: ability to hide titles

### ISSUE THREAD

**Issue by beckkake** [hyprwm/hyprland-plugins#59]
While I know the feature of hyprbars is... the titlebars, many other WMs have the ability to hide the names from the titlebars themselves, and only feature the buttons and the bar itself.
This would be a decent feature for those wanting to achieve a more minimal look.

This is an image of what that could look like.

![no titles](https://github.com/hyprwm/hyprland-plugins/assets/140576438/f511fdc3-1b56-4345-8a4d-dd7213f1cdd1)

**Comment by vaxerski** [comment]
oh, lol, text. We live in a society.

Yeah it was just a temporary idea. I'll add the option in a sec
