### ISSUE TITLE
blur does not apply to hyprbars

### ISSUE THREAD

**Issue by e-tho** [hyprwm/hyprland-plugins#61]

**Comment by Ein420** [comment]
going through the exact same thing

**Comment by radstevee** [comment]
bump! having the same issue

**Comment by vaxerski** [comment]
please don't bump but rather react with :+1:.

**Comment by Ein420** [comment]
Any updates/hopes of this being acknowledged?

**Comment by vaxerski** [comment]
feel free to mr yourself

**Comment by shadowelite-sec** [comment]
fixed ?

**Comment by vaxerski** [comment]
Just give a :+1: please stop adding noise

**Comment by vaxerski** [comment]
enjoy
