### ISSUE TITLE
Can't build hyprbars on openSUSE because of location of hyprbars

### ISSUE THREAD

**Issue by sjp760** [hyprwm/hyprland-plugins#63]
I am having trouble building a hyprbars package on openSUSE because of the location of the libinput header being different than other distros. The location of libinput.h in openSUSE /usr/include/libinput/libinput.h while on other distros it is usually /usr/include/libinput.h. 

Below are the bug reports of what they said the solution is. They said to use pkgconfig to detect the location of libinput.h and get the proper -I flag in the compiler. 

https://bugzilla.suse.com/show_bug.cgi?id=1218411
https://bugzilla.suse.com/show_bug.cgi?id=795968

**Comment by vaxerski** [comment]
does `pkg-config --cflags libinput` return the correct path for you?

**Comment by vaxerski** [comment]
feel free to make a MR when (if) you figure it out.

**Comment by vaxerski** [comment]
uhh the .pc does work for me on arch
