### ISSUE TITLE
Plugin borders-plus-plus failed to build.

### ISSUE THREAD

**Issue by cprin21** [hyprwm/hyprland-plugins#66]
```hyprpm update``` works after deleting all folders within ```/usr/include/hyprland``` but, and I don't use this plugin, borders-plus-plus fails to build.

**Comment by vaxerski** [comment]
yeah sorry there was a change regarding decos and some plugins need an update to chase hyprland. I'll fix this tomorrow.

**Comment by nathanchere** [comment]
Thanks. borders-plus-plus was still not building for me, no indication where to find logs etc, but was fixed with:

```
sudo rm -rf /usr/include/hyprland                                                                   
hyprpm update
hyprpm add https://github.com/hyprwm/hyprland-plugins
```

Maybe it would be a nice addition to include a log path or similar to the output when a hyprpm operation fails

**Comment by vaxerski** [comment]
you can add `-v` for more logs.
