### ISSUE TITLE
Error loading plugins

### ISSUE THREAD

**Issue by cprin21** [hyprwm/hyprland-plugins#69]
Hyprland version: ```Hyprland, built from branch main at commit 46997a764304366d772456c20b1c719960927aa7```

Hyprbars, and I'd assume other plugins if I were using them, does not load on this version of Hyprland.

Error message: ```[hyprbars] Failure in initialization: Version mismatch (headers ver is not equal to running hyprland ver)```

**Comment by cprin21** [comment]
There's got to be a way to update the headers for hyprland-plugins to the current hyprland git commit in an automatic way.

**Comment by cprin21** [comment]
Was able to update now.

**Comment by cprin21** [comment]
And now with  branch main at commit 42ab06e7c84fed39b3f853f213ef2966f23baaa5 plugins are broken again.

**Comment by vaxerski** [comment]
you need to recompile your plugins with every update of hyprland.

**Comment by cprin21** [comment]
Right, except the headers were not up to date. I just ran hyprpm update -n again and it worked but it wasn't working a half hour ago.

**Comment by cprin21** [comment]
Just updated Hyprland to the latest git branch again and again getting a header version mismatch error.
![240101_14-40-57](https://github.com/hyprwm/hyprland-plugins/assets/107228497/9974afc8-d9f5-49be-80ba-dd86a4dd33d2)

**Comment by cprin21** [comment]
I had to remove hyprbars, remove the repo, add the repo, then enable hyprbars again. 
Finally worked. Wish that entirely reloading the repo and building the plugins again wasn't necessary.

**Comment by vaxerski** [comment]
`hyprpm update` should update the headers. If it doesn't, that's a bug in hyprpm and not these plugins.

**Comment by cprin21** [comment]
> If it doesn't, that's a bug in hyprpm and not these plugins.
Gotcha if this happens again I'll open an issue on Hyprland's github instead of here. Thanks!
