### ISSUE TITLE
Feature Request - Window Rules for Conditionally Removing Bars

### ISSUE THREAD

**Issue by YaroKasear** [hyprwm/hyprland-plugins#70]
I am pretty happy so far with hyprbars, but one observation is that it doesn't really provide a way for me to remove the decoration from windows that either provide their own (Firefox, VS Code, etc.) or ones where they make little sense (Firefox's PiP.) 

I didn't see anything in issues or documentation on this, so I am assuming this was maybe not implemented. If that's not the case, then how can I apply these rules?

**Comment by vaxerski** [comment]
plugins can't add custom windowrules yet, I should add that, yea

**Comment by Aworldc** [comment]
yeah i only want my bars on floating windows

**Comment by Sohail-XD** [comment]
> yeah i only want my bars on floating windows

same
