### ISSUE TITLE
Hyprwinwrap CPU usage is insane

### ISSUE THREAD

**Issue by AnotherRandomGitHubAccount** [hyprwm/hyprland-plugins#79]
I think some optimization would be helpful for hyprwinwrap. without running a background program, my cpu sits around ~0.3%. with hyprwinwrap it uses ~33%, literally expending an entire core for the process of putting a window in my background.

**Comment by vaxerski** [comment]
sounds like a bug

**Comment by JonathanSteininger** [comment]
I have noticed this issue while only using kitty. Have you tried running other applications in the background? Do you get the same result?

**Comment by AnotherRandomGitHubAccount** [comment]
yes i tried it with foot and other things too. the main hyprland process (none of the threads it seems) shows 78% of a core and the actual thing (like kitty or foot) stays at like 40% (no matter what application it is, it uses around 40% somehow)
