### ISSUE TITLE
header missing

### ISSUE THREAD

**Issue by se7en-x230** [hyprwm/hyprland-plugins#86]
~ 2m 45s ❯ hyprpm -v update
[v] version returned: Hyprland, built from branch main at commit 94aeb06d6ba14d403c46b52d1d2e397acb5906a4 dirty (toplevelexport: set last damage for dmabuf copy).
Date: Thu Feb 22 10:10:01 2024
Tag: v0.35.0-69-g94aeb06d

flags: (if any)

[v] parsed commit 94aeb06d6ba14d403c46b52d1d2e397acb5906a4 at branch main

! Cloning https://github.com/hyprwm/hyprland, this might take a moment.
✔ cloned
[v] git returned: Already on 'main'
Your branch is up to date with 'origin/main'.
HEAD is now at 94aeb06d toplevelexport: set last damage for dmabuf copy

✔ checked out to running ver
! configuring Hyprland
[v] setting PREFIX for cmake to /home/seven/.local/share/hyprpm/headersRoot
[v] cmake returned: CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.Not searching for unused variables given on the command line.

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!

[v] meson returned: sh: line 1: meson: command not found

✔ configured Hyprland
[v] installation will run: sed -i -e "s#PREFIX = /usr/local#PREFIX = /home/seven/.local/share/hyprpm/headersRoot#" /tmp/hyprpm/hyprland/Makefile && cd /tmp/hyprpm/hyprland && make installheaders
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╍━━━━━━━━━  4 / 5  Installing sources[v] installer returned: You need to run make all first.
make: *** [Makefile:76: installheaders] Error 1

✖ failed to install headers with error code 2
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  5 / 5  Failed

✖ Headers missing. Please run hyprpm update to fix those.

**Comment by DupeDawn** [comment]
how did you fix this i have the same problem

**Comment by zebogan** [comment]
@se7en-x230 how did you fix this
@DupeDawn did you figure it out?
i have the same issue

**Comment by zebogan** [comment]
update: fixed it by installing gcc and g++, then running:
CC=gcc CXX=g++
