### ISSUE TITLE
Segmentation Fault in Hyprland with plugins enabled and windows in group mode

### ISSUE THREAD

**Issue by NyxTrail** [hyprwm/hyprland-plugins#92]
I get segmentation fault in Hyprland with borders-plus-plus or hyprtrails plugin enabled and close a window in a group with other windows.

## Steps to reproduce
1. Enable hyprtrail or borders-plus-plus
2. Open a bunch of windows in group mode (The specific application doesn't seem to matter. I was able to reproduce with firefox, thunar and kitty)
3. Close one of those windows or move one of the windows outside the group

```
$ hyprctl version
Hyprland, built from branch HEAD at commit 1c460e98f870676b15871fe4e5bfeb1a32a3d6d8  (props: bump ver to 0.36.0).
Date: Wed Feb 28 00:32:40 2024
Tag: v0.36.0
```

Hyprland config:
[hyprlandd.conf.txt](https://github.com/hyprwm/hyprland-plugins/files/14549158/hyprlandd.conf.txt)

Logs in debug mode:
[hyprlandCrashReport93807.txt](https://github.com/hyprwm/hyprland-plugins/files/14549154/hyprlandCrashReport93807.txt)
[hyprlandCrashReport591848.txt](https://github.com/hyprwm/hyprland-plugins/files/14549155/hyprlandCrashReport591848.txt)

**Comment by vaxerski** [comment]
fixed https://github.com/hyprwm/Hyprland/commit/0c28d4e334532e8a8edacf36bcaf4e6b973ea398
