### ISSUE TITLE
hyprwinwrap: Unable to search for function "onCommit": no symbols found in binary (is "nm" in path?)

### ISSUE THREAD

**Issue by YaroKasear** [hyprwm/hyprland-plugins#93]
I am no longer able to use the hyprwinwrap plugin as of about a week ago. I finally got around to checking my logs to see why and the following three lines jump out at me:

```
[LOG] Loading plugin /nix/store/hny19dyx3qar0rxd1j6hi13qq7qv1x3k-hyprwinwrap-0.1/lib/libhyprwinwrap.so which is now present in config
[ERR] Unable to search for function "onCommit": no symbols found in binary (is "nm" in path?)
[ERR]  [PluginSystem] Plugin /nix/store/hny19dyx3qar0rxd1j6hi13qq7qv1x3k-hyprwinwrap-0.1/lib/libhyprwinwrap.so (Handle 22ae650) crashed in init. Unloading.
[LOG]  [PluginSystem] Plugin  unloaded.
```

I am using NixOS with nixpkgs-unstable and the Hyprland flake. I tried to run `nm` and got a truckload of possible packages it comes from and unsure which one Hyprland is expecting to be there.

**Comment by vaxerski** [comment]
@fufexan for nix

you're most likely missing nm, as stated. In arch it's a part of `binutils`, dk about nix

**Comment by YaroKasear** [comment]
> @fufexan for nix
> 
> you're most likely missing nm, as stated. In arch it's a part of `binutils`, dk about nix

I tried installing it. No go.

I even tried to make a modified PATH in my config to include binutils and that didn't work either: `env=PATH,/nix/store/7hhd9smnjspppk4k6n47bkw64fdbgbrz-binutils-wrapper-2.41/bin:$PATH`

**Comment by fufexan** [comment]
Except from changing the build structure of the plugins, there wasn't any other change in Nix.

**Comment by YaroKasear** [comment]
> Except from changing the build structure of the plugins, there wasn't any other change in Nix.

Could the build structure change have caused this, maybe something that changed the environment in which the plugin is used/installed/loaded? I didn't change anything in how I installed or configured hyprwinwrap in my flake when this broke, the only thing that changed at that point was a Hyprland update. 

I'm not sure what I can do to get hyprwinwrap to work again. I already tried including binutils in home.packages (Which shouldn't be necessary as binutils would be part of any Nix/NixOS installation.) and putting `"PATH,${pkgs.binutils}/bin:$PATH"` in wayland.windowManager.hyprland.settings.env. Neither worked with the same error.

**Comment by fufexan** [comment]
Can you try `ba7d13e95564635d7769b979275701c6413c8da1` (the last commit before my changes) and see whether it still happens? If it doesn't, try to bisect.

**Comment by fufexan** [comment]
Looks like we still need to wrap Hyprland. I'll revert the changes then.

**Comment by YaroKasear** [comment]
Hyprwinwrap works now. 

I hope there might be a way to allow you to resolve the double wrapping issue without this problem.

**Comment by fufexan** [comment]
> Hyprwinwrap works now.
> 
> I hope there might be a way to allow you to resolve the double wrapping issue without this problem.

Yeah, we can simply use `hyprland-unwrapped` and manually add the required packages for wrapping.
